{% set name = "google-cloud-billing-budgets" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46566700dbf339581f467e38fcf5bda16a49df66175a823e857f00cf72f99419

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev
    - libcst >=0.2.5

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.billing
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-billingbudgets
  summary: Python Client for Google Cloud Billing Budget
  doc_url: https://googleapis.dev/python/billingbudgets/latest/index.html
  dev_url: https://github.com/googleapis/python-billingbudgets
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
