{% set name = "google-cloud-billing-budgets" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d83953eb6241c9edb3ceeeb295a3cdfa9f7ac116cf855017df428af723809294

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-api-core-grpc >=1.28.0,<3.0dev
    - proto-plus >=1.10.0

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.billing
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-billingbudgets
  summary: Python Client for Google Cloud Billing Budget
  doc_url: https://googleapis.dev/python/billingbudgets/latest/index.html
  dev_url: https://github.com/googleapis/python-billingbudgets
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
