{% set name = "google-cloud-billing-budgets" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43800951b589746e10a1738953b3c5e8e4a3d5e9051d55e03ca7c3177e4458ff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev
    - libcst >=0.2.5

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.billing
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-billingbudgets
  summary: Python Client for Google Cloud Billing Budget
  doc_url: https://googleapis.dev/python/billingbudgets/latest/index.html
  dev_url: https://github.com/googleapis/python-billingbudgets
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
